export const TRAER_USUARIOS='TRAER_USUARIOS'
export const CARGANDO_USUARIOS="CARGANDO"
export const ERROR_USUARIOS="ERROR"

export const TRAER_PUBLICACIONES="TRAER_PUBLICACIONES"
export const CARGANDO_PUBLICACIONES="CARGANDO_PUBLICACIONES"
export const ERROR_PUBLICACIONES="ERROR_UPUBLICACIONES"

export const TRAER_PUBLICACIONES_POR_USUARIO="TRAER_PUBLICACIONES_POR_USUARIO" 
export const ABRIR_COMENTARIOS_PUBLICACION="ABRIR_COMENTARIOS_PUBLICACION"
